// Process the plant data and calculate retail prices
export const plantData = [
  {
    id: 1,
    botanicalName: "Almond 'All in One'",
    commonName: "All in One Almond",
    containerSize: "10/15 gallon",
    basePrice: 72.99,
    retailPrice: 72.99 * 1.75,
    availability: 1,
  },
  {
    id: 2,
    botanicalName: "Apple 'Fuji'",
    commonName: "Fuji Apple",
    containerSize: "10/15 gallon",
    basePrice: 72.99,
    retailPrice: 72.99 * 1.75,
    availability: 1,
  },
  {
    id: 3,
    botanicalName: "Blueberry 'Emerald' Southern Highbush Mid season",
    commonName: "Emerald Blueberry",
    containerSize: "2 gallon",
    basePrice: 24.75,
    retailPrice: 24.75 * 1.75,
    availability: 1,
  },
  {
    id: 4,
    botanicalName: "Cherry Sweet 'Lapins'",
    commonName: "Lapins Sweet Cherry",
    containerSize: "15 gallon",
    basePrice: 72.99,
    retailPrice: 72.99 * 1.75,
    availability: 1,
  },
  {
    id: 5,
    botanicalName: "Dragon Fruit (White)",
    commonName: "White Dragon Fruit, Pitaya",
    containerSize: "5 gallon",
    basePrice: 26.99,
    retailPrice: 26.99 * 1.75,
    availability: 7,
  },
  {
    id: 6,
    botanicalName: "Grape Table 'Flame Seedless'",
    commonName: "Flame Seedless European Grape",
    containerSize: "5 gallon",
    basePrice: 36.99,
    retailPrice: 36.99 * 1.75,
    availability: 8,
  },
  {
    id: 7,
    botanicalName: "Guava 'Mexican White'",
    commonName: "Mexican Guava, Mexican Cream Guava",
    containerSize: "15 gallon",
    basePrice: 99.5,
    retailPrice: 99.5 * 1.75,
    availability: 1,
  },
  {
    id: 8,
    botanicalName: "Kiwi Vine Magic Hardy Combination (M/F) Prem",
    commonName: "Kiwi Magic Hardy Kiwi Combination",
    containerSize: "5 gallon",
    basePrice: 72.99,
    retailPrice: 72.99 * 1.75,
    availability: 1,
  },
  {
    id: 9,
    botanicalName: "Nectarine 'Arctic Star'",
    commonName: "Arctic Star Nectarine",
    containerSize: "15 gallon",
    basePrice: 72.99,
    retailPrice: 72.99 * 1.75,
    availability: 1,
  },
  {
    id: 10,
    botanicalName: "Nectarine 'Double Delight'",
    commonName: "Nectarine Double Delight",
    containerSize: "15 gallon",
    basePrice: 61.99,
    retailPrice: 61.99 * 1.75,
    availability: 2,
  },
  {
    id: 11,
    botanicalName: "Nectarine 'Double Delight'",
    commonName: "Nectarine Double Delight",
    containerSize: "15 gallon",
    basePrice: 61.99,
    retailPrice: 61.99 * 1.75,
    availability: 3,
  },
  {
    id: 12,
    botanicalName: "Nectarine 'Snow Queen'",
    commonName: "Snow Queen Nectarine",
    containerSize: "15 gallon",
    basePrice: 39.99,
    retailPrice: 39.99 * 1.75,
    availability: 3,
  },
  {
    id: 13,
    botanicalName: "Nectarine 'Snow Queen'",
    commonName: "Snow Queen Nectarine",
    containerSize: "15 gallon",
    basePrice: 39.99,
    retailPrice: 39.99 * 1.75,
    availability: 3,
  },
  {
    id: 14,
    botanicalName: "Olive (Olea) 'Arbequina' Standard Prem",
    commonName: "Arbequina Olive",
    containerSize: "5 gallon",
    basePrice: 67.99,
    retailPrice: 67.99 * 1.75,
    availability: 4,
  },
  {
    id: 15,
    botanicalName: "Passiflora edulis Passion Fruit",
    commonName: "Passion Fruit",
    containerSize: "5 gallon",
    basePrice: 28.99,
    retailPrice: 28.99 * 1.75,
    availability: 2,
  },
  {
    id: 16,
    botanicalName: "Peach 'Desert Gold'",
    commonName: "Desert Gold Peach",
    containerSize: "15 gallon",
    basePrice: 39.99,
    retailPrice: 39.99 * 1.75,
    availability: 2,
  },
  {
    id: 17,
    botanicalName: "Peach 'Galaxy' (Donut)",
    commonName: "Galaxy Donut Peach",
    containerSize: "15 gallon",
    basePrice: 39.99,
    retailPrice: 39.99 * 1.75,
    availability: 1,
  },
  {
    id: 18,
    botanicalName: "Peach 'Babcock'",
    commonName: "Babcock Peach",
    containerSize: "15 gallon",
    basePrice: 61.99,
    retailPrice: 61.99 * 1.75,
    availability: 1,
  },
  {
    id: 19,
    botanicalName: "Peach 'Babcock'",
    commonName: "Babcock Peach",
    containerSize: "15 gallon",
    basePrice: 61.99,
    retailPrice: 61.99 * 1.75,
    availability: 3,
  },
  {
    id: 20,
    botanicalName: "Persimmon 'Fuyu'",
    commonName: "Fuyu Asian Persimmon, Apple Persimmon",
    containerSize: "10/15 gallon",
    basePrice: 110,
    retailPrice: 110 * 1.75,
    availability: 4,
  },
  {
    id: 21,
    botanicalName: "Persimmon 'Fuyu'",
    commonName: "Fuyu Asian Persimmon, Apple Persimmon",
    containerSize: "10/15 gallon",
    basePrice: 110,
    retailPrice: 110 * 1.75,
    availability: 5,
  },
  {
    id: 22,
    botanicalName: "Plum 'Santa Rosa'",
    commonName: "Santa Rosa Plum",
    containerSize: "10/15 gallon",
    basePrice: 78.99,
    retailPrice: 78.99 * 1.75,
    availability: 4,
  },
  {
    id: 23,
    botanicalName: "Plum 'Santa Rosa'",
    commonName: "Santa Rosa Plum",
    containerSize: "10/15 gallon",
    basePrice: 78.99,
    retailPrice: 78.99 * 1.75,
    availability: 5,
  },
  {
    id: 24,
    botanicalName: "Plum 'Satsuma'",
    commonName: "Satsuma Plum",
    containerSize: "15 gallon",
    basePrice: 72.99,
    retailPrice: 72.99 * 1.75,
    availability: 1,
  },
  {
    id: 25,
    botanicalName: "Pomegranate 'Wonderful'",
    commonName: "Wonderful Pomegranate",
    containerSize: "10/15 gallon",
    basePrice: 85.99,
    retailPrice: 85.99 * 1.75,
    availability: 10,
  },
  {
    id: 26,
    botanicalName: "Pomegranate 'Wonderful'",
    commonName: "Wonderful Pomegranate",
    containerSize: "10/15 gallon",
    basePrice: 85.99,
    retailPrice: 85.99 * 1.75,
    availability: 5,
  },
  {
    id: 27,
    botanicalName: "Pomegranate 'Wonderful'",
    commonName: "Wonderful Pomegranate",
    containerSize: "5 gallon",
    basePrice: 26.99,
    retailPrice: 26.99 * 1.75,
    availability: 17,
  },
  {
    id: 28,
    botanicalName: "Pomegranate 'Wonderful'",
    commonName: "Wonderful Pomegranate",
    containerSize: "5 gallon",
    basePrice: 26.99,
    retailPrice: 26.99 * 1.75,
    availability: 8,
  },
  {
    id: 29,
    botanicalName: "Guava Strawberry Psidium (Red)",
    commonName: "Strawberry Guava",
    containerSize: "5 gallon",
    basePrice: 41.99,
    retailPrice: 41.99 * 1.75,
    availability: 1,
  },
  {
    id: 30,
    botanicalName: "Raspberry 'Heritage Red'",
    commonName: "Heritage Red Raspberry",
    containerSize: "3/5 gallon",
    basePrice: 34.99,
    retailPrice: 34.99 * 1.75,
    availability: 1,
  },
  // New plants - Avocados
  {
    id: 31,
    botanicalName: "Avocado 'Fuerte' (Type B)",
    commonName: "Fuerte Avocado, B-Type Flower",
    containerSize: "15 gallon",
    basePrice: 140,
    retailPrice: 140 * 1.75,
    availability: 1,
  },
  {
    id: 32,
    botanicalName: "Avocado 'Fuerte' (Type B)",
    commonName: "Fuerte Avocado, B-Type Flower",
    containerSize: "15 gallon",
    basePrice: 140,
    retailPrice: 140 * 1.75,
    availability: 7,
  },
  {
    id: 33,
    botanicalName: "Avocado 'Fuerte' (Type B)",
    commonName: "Fuerte Avocado, B-Type Flower",
    containerSize: "24inch/25gallon",
    basePrice: 260,
    retailPrice: 260 * 1.75,
    availability: 11,
  },
  {
    id: 34,
    botanicalName: "Avocado 'Fuerte' (Type B)",
    commonName: "Fuerte Avocado, B-Type Flower",
    containerSize: "24inch/25gallon",
    basePrice: 260,
    retailPrice: 260 * 1.75,
    availability: 5,
  },
  {
    id: 35,
    botanicalName: "Avocado 'Hass' (Type A)",
    commonName: "Hass Avocado, A-Type Flower",
    containerSize: "15 gallon",
    basePrice: 92.99,
    retailPrice: 92.99 * 1.75,
    availability: 15,
  },
  {
    id: 36,
    botanicalName: "Avocado 'Hass' (Type A)",
    commonName: "Hass Avocado, A-Type Flower",
    containerSize: "15 gallon",
    basePrice: 92.99,
    retailPrice: 92.99 * 1.75,
    availability: 7,
  },
  {
    id: 37,
    botanicalName: "Avocado 'Hass' (Type A)",
    commonName: "Hass Avocado, A-Type Flower",
    containerSize: "24inch/25gallon",
    basePrice: 465,
    retailPrice: 465 * 1.75,
    availability: 10,
  },
  {
    id: 38,
    botanicalName: "Avocado 'Hass' (Type A)",
    commonName: "Hass Avocado, A-Type Flower",
    containerSize: "24inch/25gallon",
    basePrice: 465,
    retailPrice: 465 * 1.75,
    availability: 2,
  },
  {
    id: 39,
    botanicalName: "Avocado 'Holiday' (Semi-Deciduous, Type A)",
    commonName: "Holiday Avocado, A-Type Flower",
    containerSize: "5 gallon",
    basePrice: 57.99,
    retailPrice: 57.99 * 1.75,
    availability: 1,
  },
  {
    id: 40,
    botanicalName: "Avocado 'Lamb Hass' (Type A)",
    commonName: "Lamb Hass Avocado, A-Type Flower",
    containerSize: "15 gallon",
    basePrice: 92.99,
    retailPrice: 92.99 * 1.75,
    availability: 3,
  },
  {
    id: 41,
    botanicalName: "Avocado 'Lamb Hass' (Type A)",
    commonName: "Lamb Hass Avocado, A-Type Flower",
    containerSize: "15 gallon",
    basePrice: 92.99,
    retailPrice: 92.99 * 1.75,
    availability: 0,
  },
  {
    id: 42,
    botanicalName: "Avocado 'Mexicola Grande' (Type A)",
    commonName: "Mexicola Grande Avocado, A-Type Flower",
    containerSize: "15 gallon",
    basePrice: 92.99,
    retailPrice: 92.99 * 1.75,
    availability: 6,
  },
  {
    id: 43,
    botanicalName: "Avocado 'Zutano' (Type B)",
    commonName: "Zutano Avocado, B-Type Flower",
    containerSize: "15 gallon",
    basePrice: 92.99,
    retailPrice: 92.99 * 1.75,
    availability: 9,
  },
  // Citrus plants
  {
    id: 44,
    botanicalName: "Kumquat 'Nagami' Low-Branch",
    commonName: "Nagami Kumquat",
    containerSize: "20/25 gallon",
    basePrice: 465,
    retailPrice: 465 * 1.75,
    availability: 2,
  },
  {
    id: 45,
    botanicalName: "Kumquat 'Nagami' Standard",
    commonName: "Nagami Kumquat",
    containerSize: "10/15 gallon",
    basePrice: 165,
    retailPrice: 165 * 1.75,
    availability: 6,
  },
  {
    id: 46,
    botanicalName: "Kumquat 'Nagami' Standard",
    commonName: "Nagami Kumquat",
    containerSize: "20/25 gallon",
    basePrice: 550,
    retailPrice: 550 * 1.75,
    availability: 1,
  },
  {
    id: 47,
    botanicalName: "Lemon 'Eureka' Bush",
    commonName: "Eureka Lemon",
    containerSize: "10/15 gallon",
    basePrice: 165,
    retailPrice: 165 * 1.75,
    availability: 10,
  },
  {
    id: 48,
    botanicalName: "Lemon 'Eureka' Bush",
    commonName: "Eureka Lemon",
    containerSize: "3/5 gallon",
    basePrice: 47.99,
    retailPrice: 47.99 * 1.75,
    availability: 4,
  },
  {
    id: 49,
    botanicalName: "Lemon 'Eureka' Standard",
    commonName: "Eureka Lemon",
    containerSize: "10/15 gallon",
    basePrice: 165,
    retailPrice: 165 * 1.75,
    availability: 9,
  },
  {
    id: 50,
    botanicalName: "Lemon 'Eureka Variegated Pink' Standard",
    commonName: "Pink Variegated Eureka Lemon",
    containerSize: "10/15 gallon",
    basePrice: 155,
    retailPrice: 155 * 1.75,
    availability: 6,
  },
  {
    id: 51,
    botanicalName: "Lemon 'Improved Meyer' Bush",
    commonName: "Meyer Lemon",
    containerSize: "10/15 gallon",
    basePrice: 120,
    retailPrice: 120 * 1.75,
    availability: 11,
  },
  {
    id: 52,
    botanicalName: "Lemon 'Improved Meyer' Bush",
    commonName: "Meyer Lemon",
    containerSize: "20/25 gallon",
    basePrice: 495,
    retailPrice: 495 * 1.75,
    availability: 1,
  },
  {
    id: 53,
    botanicalName: "Lemon 'Improved Meyer' Bush",
    commonName: "Meyer Lemon",
    containerSize: "5 gallon",
    basePrice: 51.99,
    retailPrice: 51.99 * 1.75,
    availability: 1,
  },
  {
    id: 54,
    botanicalName: "Lemon 'Improved Meyer' Espalier",
    commonName: "Meyer Lemon",
    containerSize: "10/15 gallon",
    basePrice: 140,
    retailPrice: 140 * 1.75,
    availability: 4,
  },
  {
    id: 55,
    botanicalName: "Lemon 'Improved Meyer' Espalier",
    commonName: "Meyer Lemon",
    containerSize: "5 gallon",
    basePrice: 72.99,
    retailPrice: 72.99 * 1.75,
    availability: 6,
  },
  {
    id: 56,
    botanicalName: "Lemon 'Improved Meyer' Standard",
    commonName: "Meyer Lemon",
    containerSize: "10/15 gallon",
    basePrice: 120,
    retailPrice: 120 * 1.75,
    availability: 16,
  },
  {
    id: 57,
    botanicalName: "Lemon 'Improved Meyer' Standard",
    commonName: "Meyer Lemon",
    containerSize: "20/25 gallon",
    basePrice: 545,
    retailPrice: 545 * 1.75,
    availability: 2,
  },
  {
    id: 58,
    botanicalName: "Lime 'Bearss' Bush",
    commonName: "Tahitian Lime, Persian Lime, Bearss Lime",
    containerSize: "10/15 gallon",
    basePrice: 165,
    retailPrice: 165 * 1.75,
    availability: 4,
  },
  {
    id: 59,
    botanicalName: "Lime 'Bearss' Standard",
    commonName: "Tahitian Lime, Persian Lime, Bearss Lime",
    containerSize: "10/15 gallon",
    basePrice: 165,
    retailPrice: 165 * 1.75,
    availability: 12,
  },
  {
    id: 60,
    botanicalName: "Lime 'Bearss' Standard",
    commonName: "Tahitian Lime, Persian Lime, Bearss Lime",
    containerSize: "20/25 gallon",
    basePrice: 545,
    retailPrice: 545 * 1.75,
    availability: 4,
  },
  {
    id: 61,
    botanicalName: "Lime 'Mexican Thornless' Bush",
    commonName: "Thornless Key Lime, Bartender's Lime",
    containerSize: "10/15 gallon",
    basePrice: 155,
    retailPrice: 155 * 1.75,
    availability: 8,
  },
  {
    id: 62,
    botanicalName: "Mandarin 'Clementine' Bush",
    commonName: "Clementine Mandarin",
    containerSize: "10/15 gallon",
    basePrice: 155,
    retailPrice: 155 * 1.75,
    availability: 3,
  },
  {
    id: 63,
    botanicalName: "Mandarin 'Frost Owari' Satsuma Standard",
    commonName: "Owari Satsuma Mandarin (Low Seeds)",
    containerSize: "20/25 gallon",
    basePrice: 545,
    retailPrice: 545 * 1.75,
    availability: 2,
  },
  {
    id: 64,
    botanicalName: "Mandarin 'Tahoe Gold' Standard",
    commonName: "Tahoe Gold Mandarin",
    containerSize: "10/15 gallon",
    basePrice: 155,
    retailPrice: 155 * 1.75,
    availability: 5,
  },
  {
    id: 65,
    botanicalName: "Orange 'Cara Cara' Standard",
    commonName: "Cara Cara Navel Orange, Red Navel",
    containerSize: "10/15 gallon",
    basePrice: 155,
    retailPrice: 155 * 1.75,
    availability: 9,
  },
  {
    id: 66,
    botanicalName: "Orange 'Midknight' Valencia Standard",
    commonName: "Midknight Valencia Orange",
    containerSize: "10/15 gallon",
    basePrice: 160,
    retailPrice: 160 * 1.75,
    availability: 5,
  },
  {
    id: 67,
    botanicalName: "Orange 'Washington' Standard",
    commonName: "Washington Navel Orange",
    containerSize: "10/15 gallon",
    basePrice: 165,
    retailPrice: 165 * 1.75,
    availability: 3,
  },
  {
    id: 68,
    botanicalName: "Pummelo 'Chandler' Standard",
    commonName: "Chandler Pummelo",
    containerSize: "20/25 gallon",
    basePrice: 260,
    retailPrice: 260 * 1.75,
    availability: 1,
  },
  {
    id: 69,
    botanicalName: "Tangelo Minneola Standard",
    commonName: "Minneola Tangelo",
    containerSize: "10/15 gallon",
    basePrice: 155,
    retailPrice: 155 * 1.75,
    availability: 4,
  },
]

